"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$os\
$shell\
$username\
$hostname\
$directory\
$git_branch\
"""

right_format = """
$cmd_duration\ 
$conda\
$time\
"""
[fill]
symbol = " "

[directory]
style = "bright-black"
truncate_to_repo = true
home_symbol = ""

[conda]
ignore_base = false
symbol = " "
format = "[using $symbol$environment](bold green) "

[username]
format = '[\[](bright-black)[$user](cyan)[\]](bright-black) '
show_always = true

[hostname]
ssh_symbol = " "

[character]
success_symbol = "[󰁔](bright-cyan)"
error_symbol = "[󰁔](bright-red)"
vimcmd_symbol = "[](green)"

[git_branch]
format = "[on $symbol$branch ]($style)"
style = "purple"
symbol = ""

[git_status]
format = "[[($conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[time]
format = "[at $time]($style) "
style = "bright-black"
disabled = false
use_12hr = true

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"
min_time = 250

[shell]
fish_indicator = "󰈺"
zsh_indicator = "󰰷"
powershell_indicator = "󰨊"
cmd_indicator = ""
bash_indicator = "󱆃"
disabled = false
style = "cyan"

[memory_usage]
symbol = "󰍛"
threshold = 0
disabled = false
style = "bright-black bold dimmed"
format = '[$symbol $ram]($style)'

[battery]
format = '[$symbol $percentage]($style) '
full_symbol = "󰁹"
charging_symbol = "󰂄"
empty_symbol = "󰂎 "
unknown_symbol = "󰂑 "

[[battery.display]]
threshold = 10
style = "bright-red"
discharging_symbol = "󰁺"

[[battery.display]]
threshold = 20
style = "red dimmed"
discharging_symbol = "󰁻"

[[battery.display]]
threshold = 30
style = "bright-yellow dimmed"
discharging_symbol = "󰁼"

[[battery.display]]
threshold = 40
style = "yellow dimmed"
discharging_symbol = "󰁽"

[[battery.display]]
threshold = 50
style = "green dimmed"
discharging_symbol = "󰁾"

[[battery.display]]
threshold = 60
style = "green dimmed"
discharging_symbol = "󰁿"

[[battery.display]]
threshold = 70
style = "bright-green dimmed"
discharging_symbol = "󰂀"

[[battery.display]]
threshold = 80
style = "bright-green dimmed"
discharging_symbol = "󰂁"

[[battery.display]]
threshold = 90
style = "bright-green dimmed"
discharging_symbol = "󰂂"

[python]
format = "[$symbol$virtualenv]($style) "
style = "bright-black"
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[os]
disabled = false
style = "bright-white"
