
[env]
TERM = 'xterm-256color'

[window]
dynamic_padding = true

decorations = "buttonless"

opacity = 0.75
blur = true

option_as_alt = "Both"

[font]
normal.family = "Hack Nerd Font"

[mouse]
hide_when_typing = true

[general]
import = ["~/.config/alacritty/themes/themes/carbonfox.toml"]
